apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: isatis-specification-api-production
  labels:
    app: isatis-specification-api
    env: production
    tier: backend
spec:
  selector:
    matchLabels:
      app: isatis-specification-api
      env: production
      tier: backend
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: isatis-specification-api
        env: production
        tier: backend
    spec:
      nodeSelector:
        env: production
        tier: backend
      containers:
      - name: isatis-specification-api
        image: isatis.azurecr.io/isatis/specification.api:20230503.1
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: APP_VERSION
            value: '20230503.1'
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1
            memory: 512Mi
      imagePullSecrets:
      - name: acr
---
apiVersion: v1
kind: Service
metadata:
  name: isatis-specification-api-production
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: isatis-specification-api
    env: production
    tier: backend